name: verificação de teste automatizado

on: 
  push:
   branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.13.0
      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar testes
        run: |
          pytest --cov=app --cov-report=term-missing --cov-fail-under=90
          
      - name: Gerar relatório simples
        run: |
          echo "Pipeline executado com sucesso!"